theme = "boo_berry"


# REFERENCE: https://docs.helix-editor.com/editor.html
[editor]
# required, otherwise set `theme` won't work in Ubuntu
true-color = true

shell = ["zsh", "-c"]
line-number = "relative"
rulers = [120]
bufferline = "multiple"
auto-save = true
#mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
